### ISSUE TITLE
Destroy user session when locking account

### ISSUE THREAD

**Issue by jesseobrien** [dre1080/warden#12]
Ideally, if an anyone locks a users account, the account should be subsequently logged out on the next request that requires a session check. I don't know how much overhead it would be but authentication tokens should be compared on each Warden::check() Upon locking it should revoke the current authentication token in the database, destroy the session immediatly, and the cookie as well.

**Comment by dre1080** [comment]
Yes, auth tokens are compared in `Warden_Driver::logged_in()` and  `Warden::check()` is run in every `Warden::_init()`

**Comment by jesseobrien** [comment]
Check https://github.com/dre1080/warden/pull/13. The auth tokens are compared, but locking isn't checked in the driver.

**Comment by dre1080** [comment]
fixed https://github.com/dre1080/warden/commit/f25e1dad5474c84516a3cb3a6d53f5a5a01fa26b
