### ISSUE TITLE
Lock issue

### ISSUE THREAD

**Issue by andreoav** [dre1080/warden#15]
When: 

lockable, in_use == false in the warden config file i'm getting this exception:

**File: model/user.php, line 224**

``` php
elseif ($record->is_access_locked()) {
    throw new Warden_Failure('locked');
}
```

The **is_access_locked()** function returns **return !$this->is_lock_expired()**, and in the function **is_lock_expired()" returns `false` when lockable is disabled... the false will be returned to the first call as true, and we have an exception even with lockable disabled

**Comment by dre1080** [comment]
Are you using the latest version of warden?

**Comment by andreoav** [comment]
Yes
