### ISSUE TITLE
Error with omniauth register

### ISSUE THREAD

**Issue by andreoav** [dre1080/warden#16]
After the the authorization with twitter or facebook is forged the view auth/register to complete the user information. When the view is forged, \Session:get('omniauth') returns the user credentials, but when I submit the form, \Session:get('omniauth') return NULL and I get this error:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'uid' cannot be null with query: "INSERT INTO `services` (`user_id`, `uid`, `provider`, `access_token`, `access_secret`, `created_at`, `updated_at`) VALUES ('3', null, null, null, null, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"

**Comment by dre1080** [comment]
Did you check if the session expired?

**Comment by andreoav** [comment]
I don't think so. I restarted the server.... and at the same time I authorize the app, I get this error. =/

**Comment by andreoav** [comment]
Worked now with another browser.

**Comment by dre1080** [comment]
Probably the browser cache.. What browser was it? Chrome?

**Comment by andreoav** [comment]
Chrome and Firefox... worked with IE.

The first time I tried with Chrome and Firefox it works perfectly. Then I do a \Warden::logout() and tried to add another account i get this error in both browsers.
