### ISSUE TITLE
Account is Locked even with Lockable Disabled...

### ISSUE THREAD

**Issue by aranw** [dre1080/warden#17]
So I installed Warden using the refine interface which automatically added everything and I went to disable Lockable in the config and then found that users were Locked? 

Fixed by reenabling lockable in the config.

**Comment by dre1080** [comment]
Yes, you're getting an exception? this was fixed in the dev branch, there was a logic issue

**Comment by aranw** [comment]
Yeah I got a exception if its fixed thats cool then :-D Ta
