### ISSUE TITLE
Lockable users

### ISSUE THREAD

**Issue by dre1080** [dre1080/warden#2]
Lockable should handle blocking user access after a certain number of attempts and prevent brute-force attacks.

Possible fields to add to users:
`locked_at`
`failed_attempts` (or maybe use trackable's `sign_in_count`?)
`unlock_token`

**Comment by rclanan** [comment]
I like the idea of tracking sign_in_count's maybe make it a config option.

**Comment by dre1080** [comment]
Yes will add that as a config option, max number of allowed attempts and maybe time in between each attempt
