### ISSUE TITLE
before_save event bug!

### ISSUE THREAD

**Issue by PrimozRome** [dre1080/warden#40]
When you save a user, a 'before_save' event kicks in inside the Warden user model, which calls _add_default_role().

This method runs an ORM query on the current user object. This will refresh the data in the object, which is a problem if you're saving permissions on the current user. That should be changed to a standard DB query to avoid ORM cache reload or update issues.

More about this and how we found this bug in this FuelPHP forum thread: http://fuelphp.com/forums/discussion/comment/13701

I will make a pull request for this one.

**Comment by dre1080** [comment]
@PrimozRome any update on the pull request for this?
