### ISSUE TITLE
Composer Package

### ISSUE THREAD

**Issue by noxify** [dre1080/warden#50]
Hi,

it would be nice if we can convert the "normal" package to an composer package
to use the "new" composer functionality inside fuelPHP.

Thanks!

**Comment by dre1080** [comment]
This would be good and easy to implement. Are you able to submit a pull request for this?

**Comment by noxify** [comment]
Currently i'm working on a new - and better - version of fuel-administrator.
But i will take a look how to "convert" it.

**Comment by dre1080** [comment]
@noxify Any progress on this?

**Comment by noxify** [comment]
Hi @dre1080 

nope... sorry :(

I tested a bit and created an "fake" composer package, which can be used via packagist.
But an ready to use composer package doesn't exists. 

I think, fuelphp in version 1.7.1 is not really composer friendly... maybe we have to wait for version 2 or using the current alpha / beta for some test cases...
