### ISSUE TITLE
Mailing support

### ISSUE THREAD

**Issue by dre1080** [dre1080/warden#7]
Add already made email template views and methods to mail users tokens etc.

**Comment by rclanan** [comment]
Have you looked into this package yet? https://github.com/fuel/email

**Comment by dre1080** [comment]
Yea, the idea was to use an already existing email package to create for example:

```
$user->send_reset_password_instructions();
```

something like that, and that method automatically generates the token, uses a View template to generate the email body and use the Email package to send the email. Wouldn't that be more efficient?

thanks

**Comment by rclanan** [comment]
Yes, I like the idea of using view templates to generate the email bodies.
